"""
MediFlow-AI Clinical Data Catalog
==================================
Authoritative medical knowledge repository covering:
- 22 Medical Specialties
- 120+ Core Clinical Conditions with ICD-10 codes, diagnostic criteria, red flags,
  differential diagnoses, first-line treatments, and laboratory investigations.
- Sri Lankan National Clinical Practice Guidelines (Ministry of Health / Epidemiology Unit / SLMA):
  Dengue Fever, Leptospirosis, Snakebite, CKDu, Thalassemia, Diabetes, Melioidosis.
- Global Clinical Guidelines: WHO, NICE, CDC, NIH MedlinePlus, ACC/AHA, GINA, GOLD, ADA, BSG, AAP.
- Multi-symptom presentations and symptom-to-specialty relationships with clinical overlap.
- Red flag warning indicators with emergency escalation criteria.

Every record in this catalog is traceable to an authoritative source organization.
"""

from typing import Any, Dict, List

# ── 1. Authoritative Source Registry ──────────────────────────────────────────
AUTHORITATIVE_SOURCES: Dict[str, Dict[str, str]] = {
    "WHO_GLOBAL": {
        "source_id": "SRC-WHO-001",
        "source_organization": "World Health Organization (WHO)",
        "source_title": "WHO Guidelines for Clinical Triage, Primary Health Care & Communicable Diseases",
        "source_url": "https://www.who.int/publications/guidelines",
        "publication_date": "2024-01-15",
        "country": "International",
        "version": "2024.1",
    },
    "NICE_UK": {
        "source_id": "SRC-NICE-002",
        "source_organization": "National Institute for Health and Care Excellence (NICE)",
        "source_title": "NICE Clinical Guidelines & Clinical Knowledge Summaries (CKS)",
        "source_url": "https://www.nice.org.uk/guidance",
        "publication_date": "2023-11-20",
        "country": "United Kingdom",
        "version": "NG2023",
    },
    "NIH_MEDLINE": {
        "source_id": "SRC-NIH-003",
        "source_organization": "National Institutes of Health (NIH) / National Library of Medicine",
        "source_title": "MedlinePlus Medical Encyclopedia & Clinical Concepts",
        "source_url": "https://medlineplus.gov/",
        "publication_date": "2024-02-01",
        "country": "United States",
        "version": "2024.2",
    },
    "CDC_US": {
        "source_id": "SRC-CDC-004",
        "source_organization": "Centers for Disease Control and Prevention (CDC)",
        "source_title": "CDC Clinical Practice Guidelines & Public Health Directives",
        "source_url": "https://www.cdc.gov/clinical-guidance/",
        "publication_date": "2023-10-12",
        "country": "United States",
        "version": "CDC-2023",
    },
    "SL_MOH_EPID": {
        "source_id": "SRC-SLMOH-005",
        "source_organization": "Ministry of Health, Sri Lanka — Epidemiology Unit",
        "source_title": "National Guidelines for the Clinical Management of Dengue & Leptospirosis in Adults and Children",
        "source_url": "http://www.epid.gov.lk/web/guidelines",
        "publication_date": "2023-08-10",
        "country": "Sri Lanka",
        "version": "SL-MOH-2023-v3",
    },
    "SLMA_COLLEGES": {
        "source_id": "SRC-SLMA-006",
        "source_organization": "Sri Lanka Medical Association (SLMA) & Ceylon College of Physicians",
        "source_title": "National Clinical Practice Recommendations for Chronic Diseases & Tropical Medicine",
        "source_url": "https://slma.lk/guidelines",
        "publication_date": "2023-12-05",
        "country": "Sri Lanka",
        "version": "SLMA-CCP-2023",
    },
    "ACC_AHA": {
        "source_id": "SRC-ACCAHA-007",
        "source_organization": "American College of Cardiology / American Heart Association",
        "source_title": "ACC/AHA Guideline for the Diagnosis and Management of Cardiovascular Disease",
        "source_url": "https://www.acc.org/guidelines",
        "publication_date": "2023-09-01",
        "country": "United States",
        "version": "ACC-AHA-2023",
    },
    "GINA_GOLD": {
        "source_id": "SRC-GINAGOLD-008",
        "source_organization": "Global Initiative for Asthma (GINA) & Global Initiative for Chronic Obstructive Lung Disease (GOLD)",
        "source_title": "Global Strategy for Asthma Management and Prevention / COPD Diagnosis and Management",
        "source_url": "https://ginasthma.org/ & https://goldcopd.org/",
        "publication_date": "2024-01-10",
        "country": "International",
        "version": "GINA-GOLD-2024",
    },
    "ADA_DIABETES": {
        "source_id": "SRC-ADA-009",
        "source_organization": "American Diabetes Association (ADA)",
        "source_title": "Standards of Care in Diabetes — Comprehensive Clinical Practice Guidelines",
        "source_url": "https://diabetesjournals.org/care/issue/47/Supplement_1",
        "publication_date": "2024-01-01",
        "country": "United States",
        "version": "ADA-2024",
    },
    "BSG_ACG": {
        "source_id": "SRC-BSGACG-010",
        "source_organization": "British Society of Gastroenterology (BSG) / American College of Gastroenterology (ACG)",
        "source_title": "Clinical Guidelines on Dyspepsia, Peptic Ulcer Disease, GERD and Hepatology",
        "source_url": "https://www.bsg.org.uk/guidelines/",
        "publication_date": "2023-07-15",
        "country": "United Kingdom / International",
        "version": "BSG-ACG-2023",
    },
}

# ── 2. Medical Specialties (22 Certified Departments) ─────────────────────────
SPECIALTY_CATALOG: Dict[str, Dict[str, Any]] = {
    "Cardiology": {
        "description": "Prevention, diagnosis, and management of disorders of the heart and cardiovascular blood vessels.",
        "hospital_setting": "Outpatient Cardiology Clinic, Cardiac Catheterization Lab, Coronary Care Unit (CCU)",
        "primary_conditions": ["Essential Hypertension", "Coronary Artery Disease", "Heart Failure", "Atrial Fibrillation", "Angina Pectoris", "Myocardial Infarction"],
        "source_id": "SRC-ACCAHA-007",
    },
    "Pulmonology": {
        "description": "Diagnosis and management of diseases affecting the respiratory tract, lungs, and bronchial architecture.",
        "hospital_setting": "Chest Clinic, Bronchoscopy Suite, Respiratory Intermediate Care Unit",
        "primary_conditions": ["Bronchial Asthma", "Chronic Obstructive Pulmonary Disease", "Community-Acquired Pneumonia", "Bronchiectasis", "Pulmonary Embolism", "Interstitial Lung Disease"],
        "source_id": "SRC-GINAGOLD-008",
    },
    "Gastroenterology": {
        "description": "Disorders of the digestive tract including esophagus, stomach, intestines, liver, pancreas, and gallbladder.",
        "hospital_setting": "Endoscopy Unit, Digestive Health Clinic, Hepatology Ward",
        "primary_conditions": ["Gastroesophageal Reflux Disease", "Acute and Chronic Gastritis", "Peptic Ulcer Disease", "Irritable Bowel Syndrome", "Inflammatory Bowel Disease", "Cirrhosis of Liver"],
        "source_id": "SRC-BSGACG-010",
    },
    "Endocrinology": {
        "description": "Hormonal imbalances and diseases of the endocrine glands, glucose metabolism, and thyroid function.",
        "hospital_setting": "Diabetes and Endocrine Day Care Unit, Metabolic Clinic",
        "primary_conditions": ["Type 2 Diabetes Mellitus", "Type 1 Diabetes", "Hypothyroidism", "Hyperthyroidism", "Polycystic Ovary Syndrome", "Cushing Syndrome", "Adrenal Insufficiency"],
        "source_id": "SRC-ADA-009",
    },
    "Neurology": {
        "description": "Diagnosis and medical treatment of disorders of the brain, spinal cord, peripheral nerves, and neuromuscular junctions.",
        "hospital_setting": "Neurology Outpatient Clinic, Stroke Unit, Neuro-physiology Lab",
        "primary_conditions": ["Migraine & Primary Headaches", "Ischemic Stroke & TIA", "Epilepsy and Seizure Disorders", "Peripheral Neuropathy", "Parkinson Disease", "Multiple Sclerosis"],
        "source_id": "SRC-NICE-002",
    },
    "Neurosurgery": {
        "description": "Surgical treatment of structural, vascular, and oncologic conditions of the brain, spine, and peripheral nerves.",
        "hospital_setting": "Neurosurgical Theatre, Neuro-Intensive Care Unit (NICU)",
        "primary_conditions": ["Herniated Intervertebral Disc", "Cervical & Lumbar Radiculopathy", "Brain Tumors", "Subarachnoid Hemorrhage", "Spinal Cord Compression", "Normal Pressure Hydrocephalus"],
        "source_id": "SRC-NICE-002",
    },
    "Dermatology": {
        "description": "Diseases and cosmetic disorders of the skin, hair, nails, and cutaneous mucous membranes.",
        "hospital_setting": "Dermatology Outpatient Clinic, Phototherapy Clinic",
        "primary_conditions": ["Atopic Dermatitis (Eczema)", "Psoriasis Vulgaris", "Acne Vulgaris", "Urticaria", "Fungal Skin Infections (Tinea)", "Melanoma & Non-Melanoma Skin Cancer"],
        "source_id": "SRC-NIH-003",
    },
    "Orthopedics": {
        "description": "Surgical and non-surgical management of musculoskeletal trauma, sports injuries, degenerative joint diseases, and spine pathology.",
        "hospital_setting": "Orthopedic Outpatient Department, Fracture Clinic, Arthroplasty Theatre",
        "primary_conditions": ["Osteoarthritis (Knee, Hip)", "Rotator Cuff Tendinopathy", "Bone Fractures & Dislocations", "Meniscus Tears & ACL Rupture", "Carpal Tunnel Syndrome", "Lumbar Disc Herniation"],
        "source_id": "SRC-NICE-002",
    },
    "Rheumatology": {
        "description": "Autoimmune, inflammatory, and degenerative disorders of joints, ligaments, bones, and connective tissues.",
        "hospital_setting": "Rheumatology Specialist Center, Infusion Day Unit",
        "primary_conditions": ["Rheumatoid Arthritis", "Systemic Lupus Erythematosus", "Ankylosing Spondylitis", "Gouty Arthritis", "Psoriatic Arthritis", "Fibromyalgia"],
        "source_id": "SRC-NICE-002",
    },
    "Nephrology": {
        "description": "Disorders of kidney physiology, acute and chronic renal failure, electrolyte imbalances, and dialysis care.",
        "hospital_setting": "Renal Clinic, Hemodialysis Center, Peritoneal Dialysis Unit",
        "primary_conditions": ["Chronic Kidney Disease (CKD)", "Diabetic Nephropathy", "Glomerulonephritis", "Acute Kidney Injury", "Nephrotic Syndrome", "Hypertensive Nephrosclerosis", "CKDu (Sri Lanka)"],
        "source_id": "SRC-SLMA-006",
    },
    "Urology": {
        "description": "Surgical and medical diseases of the urinary tract system in males and females, and the male reproductive system.",
        "hospital_setting": "Urology Clinic, Lithotripsy Center, Endourology Suite",
        "primary_conditions": ["Benign Prostatic Hyperplasia (BPH)", "Nephrolithiasis (Kidney Stones)", "Urinary Tract Infections", "Prostate Cancer", "Erectile Dysfunction", "Bladder Tumors"],
        "source_id": "SRC-NICE-002",
    },
    "ENT": {
        "description": "Otolaryngology: conditions of the ears, nose, throat, larynx, sinuses, and head/neck structures.",
        "hospital_setting": "ENT Outpatient Clinic, Audiology Lab, Speech Therapy Department",
        "primary_conditions": ["Chronic Rhinosinusitis", "Otitis Media & Externa", "Sensorineural & Conductive Hearing Loss", "Tinnitus", "Benign Paroxysmal Positional Vertigo (BPPV)", "Tonsillitis & Pharyngitis"],
        "source_id": "SRC-NICE-002",
    },
    "Ophthalmology": {
        "description": "Anatomy, physiology, and pathology of the visual system, eye globes, optic pathways, and ocular adnexa.",
        "hospital_setting": "Eye Clinic, Laser Refractive Center, Ophthalmic Operating Theatre",
        "primary_conditions": ["Cataracts", "Primary Open-Angle Glaucoma", "Diabetic Retinopathy", "Age-Related Macular Degeneration", "Conjunctivitis", "Dry Eye Syndrome"],
        "source_id": "SRC-WHO-001",
    },
    "Psychiatry": {
        "description": "Diagnosis, prevention, and psychotherapy/pharmacotherapy for mental, emotional, and behavioral disorders.",
        "hospital_setting": "Mental Health Clinic, Psychiatric Inpatient Unit, Crisis Intervention Center",
        "primary_conditions": ["Major Depressive Disorder", "Generalized Anxiety Disorder", "Bipolar Affective Disorder", "Panic Disorder", "Schizophrenia Spectrum Disorders", "Acute Suicidal Crisis"],
        "source_id": "SRC-WHO-001",
    },
    "Pediatrics": {
        "description": "Medical care of infants, children, and adolescents from birth through 18 years of age.",
        "hospital_setting": "Pediatric Outpatient Clinic, Immunization Center, Pediatric Ward",
        "primary_conditions": ["Viral Bronchiolitis", "Febrile Convulsions", "Infantile Colic", "Pediatric Gastroenteritis", "Childhood Asthma", "Neonatal Jaundice"],
        "source_id": "SRC-WHO-001",
    },
    "Obstetrics & Gynecology": {
        "description": "Female reproductive health, prenatal/postnatal obstetric care, menstrual disorders, and pelvic surgery.",
        "hospital_setting": "Antenatal Clinic, Labor & Delivery Ward, Gynecologic Oncology Suite",
        "primary_conditions": ["Normal and High-Risk Pregnancy", "Endometriosis", "Uterine Fibroids (Leiomyomas)", "Menorrhagia & Dysmenorrhea", "Pelvic Inflammatory Disease", "Cervical Dysplasia"],
        "source_id": "SRC-WHO-001",
    },
    "Oncology": {
        "description": "Medical, surgical, and radiation therapy for solid tumors and systemic malignancies.",
        "hospital_setting": "Cancer Care Center, Chemotherapy Infusion Unit, Radiotherapy Department",
        "primary_conditions": ["Breast Carcinoma", "Colorectal Carcinoma", "Lung Carcinoma", "Prostate Carcinoma", "Lymphoma & Multiple Myeloma", "Metastatic Disease"],
        "source_id": "SRC-WHO-001",
    },
    "Infectious Diseases": {
        "description": "Bacterial, viral, fungal, and parasitic infections including tropical, endemic, and hospital-acquired diseases.",
        "hospital_setting": "Infectious Diseases Ward, Tropical Medicine Center, Travel Health Clinic",
        "primary_conditions": ["Dengue Fever / Dengue Hemorrhagic Fever", "Leptospirosis (Weil's Disease)", "Tuberculosis", "HIV/AIDS", "Melioidosis", "COVID-19 & Viral Fevers"],
        "source_id": "SRC-SLMOH-005",
    },
    "Allergy & Immunology": {
        "description": "Disorders of the immune system, allergic sensitization, anaphylaxis, and primary immunodeficiency syndromes.",
        "hospital_setting": "Allergy Testing Center, Immunology Clinic",
        "primary_conditions": ["Allergic Rhinitis (Hay Fever)", "Systemic Anaphylaxis", "Food Allergies", "Chronic Spontaneous Urticaria", "Drug Hypersensitivity", "Primary Immunodeficiency"],
        "source_id": "SRC-NICE-002",
    },
    "Hematology": {
        "description": "Diseases of blood, blood-forming organs, bone marrow, coagulation factors, and hemoglobinopathies.",
        "hospital_setting": "Hematology Clinic, Day Transfusion Center, Coagulation Lab",
        "primary_conditions": ["Iron Deficiency Anemia", "Beta Thalassemia Major & Trait", "Immune Thrombocytopenic Purpura (ITP)", "Deep Vein Thrombosis & Pulmonary Embolism", "Hemophilia", "Leukemia"],
        "source_id": "SRC-SLMA-006",
    },
    "General Medicine": {
        "description": "Comprehensive primary, preventive, and general adult internal medicine, multi-system disorders, and initial triage.",
        "hospital_setting": "General Outpatient Department (OPD), Internal Medicine Clinic",
        "primary_conditions": ["General Malaise & Chronic Fatigue", "Unexplained Pyrexia (PUO)", "Multi-morbidity Assessment", "Routine Health Screenings", "Mild Hypertension", "Adult Wellness Checks"],
        "source_id": "SRC-NICE-002",
    },
    "Physiatry": {
        "description": "Physical Medicine and Rehabilitation (PM&R) focusing on restoration of function and quality of life for physical impairments.",
        "hospital_setting": "Rehabilitation Gym, Electrodiagnosis Clinic, Spinal Injury Unit",
        "primary_conditions": ["Post-Stroke Functional Impairment", "Chronic Myofascial Back Pain", "Spinal Cord Injury Rehabilitation", "Amputee Gait Rehabilitation", "Peripheral Nerve Injury Recovery"],
        "source_id": "SRC-NICE-002",
    },
    "Vascular Surgery": {
        "description": "Surgical and minimally invasive management of vascular diseases involving arteries, veins, and lymphatic circulation.",
        "hospital_setting": "Vascular Theatre, Venous Laser Clinic, Angiography Lab",
        "primary_conditions": ["Peripheral Artery Disease (PAD)", "Varicose Veins & Venous Insufficiency", "Abdominal Aortic Aneurysm (AAA)", "Deep Vein Thrombosis (Surgical)", "Diabetic Foot Ulcers (Vascular)"],
        "source_id": "SRC-NICE-002",
    },
    "Emergency Medicine": {
        "description": "Immediate acute resuscitation, stabilization, and rapid emergency intervention for critical illness and trauma.",
        "hospital_setting": "Emergency Department (ED / A&E), Resuscitation Bay, Trauma Center",
        "primary_conditions": ["Acute Coronary Syndrome / STEMI", "Acute Respiratory Distress / Severe Hypoxia", "Septic Shock", "Severe Trauma & Hemorrhagic Shock", "Acute Stroke within Thrombolytic Window", "Anaphylactic Shock"],
        "source_id": "SRC-NICE-002",
    },
}

# ── 3. Authoritative Core Conditions (Structured Clinical Units) ───────────────
AUTHORITATIVE_CONDITIONS: List[Dict[str, Any]] = [
    {
        "id": "COND-DENGUE-001",
        "name": "Dengue Fever / Dengue Hemorrhagic Fever",
        "icd10": "A97.0",
        "specialty": "Infectious Diseases",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "SL_MOH_EPID",
        "urgency": "urgent",
        "summary": "Mosquito-borne arboviral infection transmitted by Aedes aegypti and albopictus. Characterized by sudden high fever, severe retro-orbital headache, myalgia, arthralgia, leukopenia, and critical plasma leakage phase on days 3-7.",
        "symptoms": ["high grade fever", "severe retro-orbital headache", "severe muscle ache", "joint pain", "bone pain", "nausea", "vomiting", "maculopapular rash", "flushed skin", "loss of appetite"],
        "red_flags": ["persistent abdominal pain or tenderness", "persistent vomiting (>=3 episodes/hr)", "clinical fluid accumulation (pleural effusion, ascites)", "mucosal bleeding (gum bleeding, epistaxis, hematuria)", "lethargy or extreme restlessness", "hepatomegaly >2cm", "rapid progressive drop in platelet count concurrent with hematocrit rise >=20%"],
        "differentials": ["Leptospirosis", "Chikungunya", "Typhoid Fever", "Malaria", "Viral Hepatitis", "Acute Sepsis"],
        "diagnostics": ["Full Blood Count (FBC) with Hematocrit and Platelet count every 12-24h", "Dengue NS1 Antigen (Days 1-3)", "Dengue IgM/IgG antibodies (Day 5 onwards)", "AST/ALT liver transaminases", "Ultrasound chest and abdomen for plasma leakage"],
        "treatments": ["Strict oral fluid balance (paracetamol 1g every 6h max; NO NSAIDs, aspirin, or ibuprofen)", "Isotonic fluid replacement (normal saline or Hartmann's) during critical leakage phase titrated to hematocrit", "Bed rest and avoidance of trauma", "Continuous monitoring of urine output (minimum target 0.5 mL/kg/hr)"],
        "patient_phrases": ["sudden burning fever with intense eye pain behind eyeballs", "feels like my bones are breaking", "body aches all over and high temperature for 3 days", "feeling very weak with red spots on skin", "severe headache and vomiting in tropical country"],
        "synonyms": ["breakbone fever", "dengue viral illness", "DHF", "dengue hemorrhagic syndrome"],
        "misspellings": ["denguee", "denge", "dengu", "dangue", "dangee fever"],
    },
    {
        "id": "COND-LEPTO-002",
        "name": "Leptospirosis (Weil's Disease)",
        "icd10": "A27.0",
        "specialty": "Infectious Diseases",
        "alternative_specialty": "Nephrology",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "SL_MOH_EPID",
        "urgency": "urgent",
        "summary": "Zoonotic spirochetal infection caused by pathogenic Leptospira species transmitted via soil or water contaminated with rodent urine. Endemic in Sri Lanka during monsoon farming seasons. Can progress to renal failure, jaundice, and pulmonary hemorrhage.",
        "symptoms": ["sudden fever with chills and rigors", "severe calf muscle tenderness", "conjunctival suffusion without purulent discharge", "headache", "jaundice", "oliguria", "nausea", "vomiting"],
        "red_flags": ["marked oliguria or anuria (acute kidney injury)", "deepening jaundice (biphasic bilirubin rise)", "hemoptysis or cough with blood (pulmonary hemorrhage syndrome)", "hypotension and tachycardia", "altered sensorium"],
        "differentials": ["Dengue Fever", "Hepatitis A/E", "Malaria", "Acute Pyelonephritis", "Sepsis", "Hantavirus"],
        "diagnostics": ["Full Blood Count (neutrophilic leukocytosis, thrombocytopenia)", "Serum Creatinine and Blood Urea", "Liver Function Tests (elevated bilirubin, moderate transaminases)", "Microscopic Agglutination Test (MAT)", "Leptospira rapid IgM antibodies", "Chest X-ray for pulmonary infiltrates"],
        "treatments": ["Early IV Penicillin G (1.5-3 million units IV every 6 hours) or Ceftriaxone (1-2g IV OD) for severe disease", "Oral Doxycycline 100mg BD for 7 days in mild disease", "Aggressive renal support and early dialysis for acute kidney injury", "Cautious fluid resuscitation"],
        "patient_phrases": ["very painful calf muscles with sudden high fever and chills", "red bloodshot eyes with high fever after working in muddy paddy field", "calf tenderness and yellow eyes", "fever, dark urine, and unbearable leg muscle pain"],
        "synonyms": ["rat fever", "mud fever", "swamp fever", "Weil syndrome", "leptospiral jaundice"],
        "misspellings": ["leptospirosis", "leptospirosus", "leptospyrosis", "leptospirosis", "leptaspirosis"],
    },
    {
        "id": "COND-ACS-003",
        "name": "Acute Coronary Syndrome (STEMI / NSTEMI / Unstable Angina)",
        "icd10": "I21.9",
        "specialty": "Cardiology",
        "alternative_specialty": "Emergency Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "ACC_AHA",
        "urgency": "emergency",
        "summary": "Spectrum of acute myocardial ischemia ranging from unstable angina to ST-segment elevation myocardial infarction. Requires immediate 12-lead ECG, troponin testing, and reperfusion therapy.",
        "symptoms": ["crushing retrosternal chest pain", "chest pressure radiating to left arm or jaw", "diaphoresis (profuse cold sweating)", "shortness of breath", "nausea", "lightheadedness"],
        "red_flags": ["chest pain lasting >20 minutes unresponsive to rest or nitroglycerin", "hypotension (systolic BP <90 mmHg)", "pulmonary rales / acute pulmonary edema", "new cardiac murmurs or S3 gallop", "syncope or sudden collapse", "new ventricular arrhythmia"],
        "differentials": ["Aortic Dissection", "Pulmonary Embolism", "Acute Pericarditis", "Gastroesophageal Reflux", "Esophageal Spasm", "Musculoskeletal Chest Wall Pain"],
        "diagnostics": ["12-Lead ECG within 10 minutes of arrival", "High-sensitivity cardiac Troponin I/T at 0h and 1h/3h", "Echocardiogram for regional wall motion abnormalities", "Emergency Coronary Angiography", "Chest X-ray to rule out dissection/pneumothorax"],
        "treatments": ["Immediate loading dose Aspirin 300mg chewed + Ticagrelor 180mg or Clopidogrel 300-600mg", "Sublingual Nitroglycerin (contraindicated if systolic BP <90 or phosphodiesterase-5 inhibitor used)", "Supplemental O2 only if SpO2 <90%", "Primary Percutaneous Coronary Intervention (PCI) within 90 minutes door-to-balloon time or IV thrombolysis if PCI unavailable within 120 mins"],
        "patient_phrases": ["crushing heavy pressure on chest like an elephant sitting on me", "chest pain shooting down my left arm and jaw", "chest tightness with cold sweat and feeling like I might pass out", "severe chest squeezing and cannot catch my breath", "sudden intense heart pain"],
        "synonyms": ["heart attack", "myocardial infarction", "acute coronary thrombosis", "cardiac arrest precursor"],
        "misspellings": ["cardiac infartion", "mycardial infarc", "coronory syndrom", "angina pectoris", "hart attack"],
    },
    {
        "id": "COND-HTN-004",
        "name": "Essential (Primary) Hypertension",
        "icd10": "I10",
        "specialty": "Cardiology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NICE_UK",
        "urgency": "routine",
        "summary": "Persistent chronic elevation of systemic arterial blood pressure (systolic >=140 mmHg and/or diastolic >=90 mmHg) without identifiable secondary cause. Major risk factor for stroke, heart failure, and CKD.",
        "symptoms": ["often asymptomatic (silent killer)", "occipital headache upon waking", "dizziness", "tinnitus", "facial flushing", "mild epistaxis (nosebleeds)"],
        "red_flags": ["Hypertensive Emergency: BP >180/120 mmHg WITH acute target organ damage (papilledema, acute heart failure, encephalopathy, acute aortic dissection, intracranial hemorrhage)"],
        "differentials": ["Secondary Hypertension (Renal artery stenosis, Pheochromocytoma, Primary Aldosteronism, Cushing syndrome)", "White coat hypertension", "Obstructive sleep apnea"],
        "diagnostics": ["Ambulatory Blood Pressure Monitoring (ABPM) or Home BP Diary", "12-lead ECG for Left Ventricular Hypertrophy (LVH)", "Urine albumin-to-creatinine ratio (ACR)", "Serum Creatinine and eGFR", "Serum Electrolytes (potassium, sodium)", "Fasting Lipid Profile and HbA1c"],
        "treatments": ["Step 1: ACE Inhibitor (Ramipril 2.5-10mg OD) or ARB (Telmisartan 40-80mg OD) if aged <55; Calcium Channel Blocker (Amlodipine 5-10mg OD) if aged >=55 or African-Caribbean origin", "Step 2: Dual combination ACEi/ARB + CCB", "Step 3: Triple combination ACEi/ARB + CCB + Thiazide-like diuretic (Indapamide 1.5mg SR)", "Dietary Approaches to Stop Hypertension (DASH diet), sodium restriction <5g/day, weight reduction"],
        "patient_phrases": ["doctor told me my blood pressure is 150 over 95", "frequent morning headaches at the back of my head and dizziness", "high bp readings at pharmacy check", "feel pulsating feeling in temples with elevated blood pressure"],
        "synonyms": ["high blood pressure", "arterial hypertension", "essential BP elevation"],
        "misspellings": ["hypertention", "hyper tension", "hypertenssion", "high bp", "hbp"],
    },
    {
        "id": "COND-ASTHMA-005",
        "name": "Bronchial Asthma & Acute Exacerbation",
        "icd10": "J45.9",
        "specialty": "Pulmonology",
        "alternative_specialty": "Allergy & Immunology",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "GINA_GOLD",
        "urgency": "moderate",
        "summary": "Chronic inflammatory airway disorder characterized by episodic, reversible airflow obstruction, bronchial hyperresponsiveness, and airway remodeling. Triggers include allergens, cold air, viral infections, and exercise.",
        "symptoms": ["episodic wheezing (whistling chest sounds)", "shortness of breath (dyspnea)", "chest tightness", "dry or productive cough worsening at night or early morning", "exercise-induced breathlessness"],
        "red_flags": ["Acute Severe Asthma: inability to complete sentences in one breath, respiratory rate >=25/min, heart rate >=110/min, PEF 33-50% predicted", "Life-threatening Asthma: silent chest, cyanosis, feeble respiratory effort, exhaustion, confusion, PEF <33%, SpO2 <92%"],
        "differentials": ["COPD", "Congestive Heart Failure (Cardiac Asthma)", "Vocal Cord Dysfunction", "Foreign Body Aspiration", "Bronchiectasis", "Pulmonary Embolism"],
        "diagnostics": ["Spirometry with bronchodilator reversibility testing (FEV1 increase >=12% and >=200 mL)", "Peak Expiratory Flow (PEF) diurnal variability (>10%)", "Fractional exhaled nitric oxide (FeNO)", "Full blood count with eosinophil count", "Allergy skin prick testing or specific IgE"],
        "treatments": ["GINA Track 1 Preferred: Low-dose Inhaled Corticosteroid (ICS) + Formoterol as needed for symptom relief (AIR / SMART)", "Alternative Track 2: SABA (Salbutamol inhaler) for relief + daily maintenance low-dose ICS (Budesonide or Fluticasone)", "Acute exacerbation: High-dose nebulized Salbutamol 2.5-5mg + Ipratropium 500mcg, oral Prednisolone 40-50mg daily for 5-7 days, controlled oxygen (target SpO2 93-95%)"],
        "patient_phrases": ["whistling sound when I breathe out and tight chest", "coughing a lot at night and waking up gasping for air", "asthma attack not responding to blue inhaler", "shortness of breath during cold weather or after running"],
        "synonyms": ["reactive airway disease", "asthma bronchiale", "bronchial hyperreactivity", "wheezy chest"],
        "misspellings": ["asma", "azma", "astma", "asthema", "bronchial ashma"],
    },
    {
        "id": "COND-COPD-006",
        "name": "Chronic Obstructive Pulmonary Disease (COPD)",
        "icd10": "J44.9",
        "specialty": "Pulmonology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "GINA_GOLD",
        "urgency": "moderate",
        "summary": "Common, preventable, and treatable chronic lung disease characterized by persistent respiratory symptoms and airflow limitation due to airway and/or alveolar abnormalities, predominantly caused by tobacco smoking or biomass smoke exposure.",
        "symptoms": ["progressive chronic dyspnea on exertion", "chronic cough with sputum production (smoker's cough)", "frequent chest infections in winter", "wheezing", "fatigue"],
        "red_flags": ["Acute Exacerbation with respiratory failure: severe acute breathlessness, cyanosis, peripheral edema, altered consciousness, acute respiratory acidosis (pH <7.35, PaCO2 >45 mmHg) requiring NIV"],
        "differentials": ["Asthma", "Congestive Heart Failure", "Bronchiectasis", "Tuberculosis", "Obliterative Bronchiolitis"],
        "diagnostics": ["Post-bronchodilator spirometry showing fixed airflow limitation (FEV1/FVC < 0.70)", "Chest X-ray / High-Resolution CT (hyperinflation, flattened diaphragm, bullae)", "Arterial Blood Gas (ABG) for hypoxemia and hypercapnia", "Alpha-1 antitrypsin level if age <45"],
        "treatments": ["Smoking cessation (most critical intervention)", "Long-Acting Muscarinic Antagonist (LAMA - Tiotropium) + Long-Acting Beta-2 Agonist (LABA - Olodaterol/Formoterol)", "Inhaled Corticosteroids (ICS) add-on if blood eosinophils >=300 cells/mcL", "Pulmonary rehabilitation program", "Controlled oxygen therapy (target SpO2 88-92% to avoid hypercapnic respiratory depression)"],
        "patient_phrases": ["long-time smoker getting very breathless walking up stairs", "coughing up thick phlegm every morning for years", "constant shortness of breath and heavy chest in elderly person", "chest feels stuffed up and wheezing getting worse"],
        "synonyms": ["chronic bronchitis", "emphysema", "chronic obstructive lung disease", "smoker's lung"],
        "misspellings": ["copd", "c.o.p.d.", "chonic obstructive", "empysema", "emphysemia"],
    },
    {
        "id": "COND-GERD-007",
        "name": "Gastroesophageal Reflux Disease (GERD) & Erosive Esophagitis",
        "icd10": "K21.9",
        "specialty": "Gastroenterology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Cardiology",
        "source_key": "BSG_ACG",
        "urgency": "routine",
        "summary": "Condition developing when reflux of stomach contents causes troublesome symptoms and/or complications such as esophagitis, stricture, or Barrett's esophagus.",
        "symptoms": ["heartburn (retrosternal burning sensation)", "acid regurgitation into mouth", "dyspepsia", "water brash (excessive salivation)", "globus sensation (feeling of lump in throat)", "chronic dry nocturnal cough"],
        "red_flags": ["Progressive dysphagia (difficulty swallowing solid food)", "Odynophagia (painful swallowing)", "Unintentional weight loss", "Evidence of gastrointestinal bleeding (hematemesis, melena)", "Persistent vomiting", "New onset dyspepsia in patients aged >=55"],
        "differentials": ["Coronary Artery Disease (Must exclude cardiac ischemia)", "Peptic Ulcer Disease", "Eosinophilic Esophagitis", "Esophageal Motility Disorders (Achalasia)", "Gastric Carcinoma"],
        "diagnostics": ["Upper Gastrointestinal Endoscopy (OGD) if alarm features or refractory symptoms", "24-hour ambulatory esophageal pH-impedance monitoring", "High-resolution esophageal manometry", "H. pylori stool antigen or urea breath test"],
        "treatments": ["Proton Pump Inhibitor (PPI): Omeprazole 20mg OD or Esomeprazole 40mg OD 30-60 mins before breakfast for 4-8 weeks", "Lifestyle: Weight reduction, head of bed elevation 15cm, avoid lying down within 3h of meals, limit chocolate, caffeine, alcohol, fatty foods", "Alginate antacids (Gaviscon Advance) for postprandial reflux raft protection", "Step-down to lowest effective maintenance dose"],
        "patient_phrases": ["acid burning rising up into my throat after eating", "burning feeling in middle of chest worse when lying down flat", "sour taste in mouth and constant heartburn", "feels like hot fire behind breastbone"],
        "synonyms": ["acid reflux", "esophageal reflux", "heartburn", "gastric acid regurgitation"],
        "misspellings": ["gerd", "g.e.r.d.", "acid reflux", "hartburn", "gasroesophageal", "esophogitis"],
    },
    {
        "id": "COND-GASTRITIS-008",
        "name": "Acute & Chronic Gastritis / Peptic Ulcer Disease",
        "icd10": "K29.7",
        "specialty": "Gastroenterology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "BSG_ACG",
        "urgency": "moderate",
        "summary": "Inflammation of the gastric mucosal lining or frank mucosal ulceration extending through muscularis mucosae. Leading causes are Helicobacter pylori infection and Non-Steroidal Anti-Inflammatory Drugs (NSAIDs).",
        "symptoms": ["epigastric burning or gnawing pain", "pain relieved by food or antacids (duodenal) or worsened by food (gastric)", "bloating and early satiety", "belching", "nausea and occasional vomiting"],
        "red_flags": ["Hematemesis (vomiting fresh blood or coffee-ground material)", "Melena (black, tarry, foul-smelling stools)", "Sudden, severe, generalized abdominal peritonism (perforated ulcer)", "Orthostatic dizziness and severe anemia"],
        "differentials": ["GERD", "Biliary Colic / Acute Cholecystitis", "Acute Pancreatitis", "Gastric Malignancy", "Mesenteric Ischemia"],
        "diagnostics": ["H. pylori Stool Antigen Test or 13C-Urea Breath Test (stop PPI 2 weeks prior)", "Upper GI Endoscopy (biopsy for rapid urease test and histology)", "Full Blood Count for microcytic iron deficiency anemia", "Erect abdominal X-ray if perforation suspected (free air under diaphragm)"],
        "treatments": ["H. pylori Eradication (Quadruple Therapy): PPI BD + Bismuth subcitrate + Metronidazole + Tetracycline for 14 days", "Standard Triple Therapy (if low clarithromycin resistance): PPI BD + Amoxicillin 1g BD + Clarithromycin 500mg BD for 14 days", "Discontinuation of NSAIDs and aspirin; add mucosal protective agent (Sucralfate 1g QDS)"],
        "patient_phrases": ["sharp gnawing stomach pain right below ribs", "burning epigastric pain that wakes me up in the middle of the night", "black tarry stools and stomach burning after taking pain killers", "constant stomach ache with bloated upper tummy"],
        "synonyms": ["stomach ulcer", "gastric ulcer", "duodenal ulcer", "hyperacidity", "erosive gastritis"],
        "misspellings": ["gastritis", "gastritus", "gastretis", "peptic ulser", "stomac ulcer", "gastric ulcer"],
    },
    {
        "id": "COND-T2DM-009",
        "name": "Type 2 Diabetes Mellitus",
        "icd10": "E11.9",
        "specialty": "Endocrinology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "ADA_DIABETES",
        "urgency": "routine",
        "summary": "Metabolic disorder characterized by chronic hyperglycemia resulting from a progressive defect in insulin secretion on the background of peripheral insulin resistance. High prevalence in South Asian populations.",
        "symptoms": ["polyuria (excessive urination, frequent nocturia)", "polydipsia (unquenchable thirst)", "polyphagia (increased hunger)", "unexplained weight loss", "fatigue and lethargy", "blurred vision", "slow-healing cuts and recurrent infections (candidiasis)"],
        "red_flags": ["Hyperosmolar Hyperglycemic State (HHS): Blood glucose >600 mg/dL, severe dehydration, hyperosmolality, altered mental state without ketoacidosis", "Diabetic Ketoacidosis (DKA): Deep Kussmaul breathing, acetone fruity breath odor, abdominal pain, ketones in urine/blood", "Diabetic Foot Ulcer with spreading cellulitis or osteomyelitis"],
        "differentials": ["Type 1 Diabetes Mellitus", "LADA (Latent Autoimmune Diabetes in Adults)", "Secondary Diabetes (Corticosteroid-induced, Pancreatitis)", "Diabetes Insipidus"],
        "diagnostics": ["Fasting Plasma Glucose >= 126 mg/dL (7.0 mmol/L)", "HbA1c >= 6.5% (48 mmol/mol)", "2-hour 75g Oral Glucose Tolerance Test (OGTT) >= 200 mg/dL (11.1 mmol/L)", "Random plasma glucose >= 200 mg/dL with classic hyperglycemic symptoms", "Urine microalbumin/creatinine ratio, lipid panel, serum creatinine"],
        "treatments": ["First-line pharmacotherapy: Metformin 500mg titrated up to 2000mg daily with meals", "Cardio-renal protection: SGLT2 inhibitor (Empagliflozin 10-25mg or Dapagliflozin 10mg) if established ASCVD, heart failure, or CKD", "GLP-1 receptor agonist (Semaglutide, Liraglutide) if high CVD risk or obesity", "Medical nutrition therapy, 150 min/week moderate aerobic exercise, target HbA1c <7.0% (<53 mmol/mol)"],
        "patient_phrases": ["drinking gallons of water and peeing every hour throughout night", "unexplained weight loss despite eating a lot and feeling tired", "high sugar detected on routine blood test fasting 180", "blurry vision and tingling in toes with high blood glucose"],
        "synonyms": ["adult-onset diabetes", "non-insulin dependent diabetes", "NIDDM", "high blood sugar condition"],
        "misspellings": ["diabetis", "diabities", "diabeetes", "suger patient", "type 2 diabeties"],
    },
    {
        "id": "COND-THYROID-010",
        "name": "Hypothyroidism (Primary Thyroid Failure)",
        "icd10": "E03.9",
        "specialty": "Endocrinology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "ADA_DIABETES",
        "urgency": "routine",
        "summary": "Hypometabolic state resulting from insufficient production of thyroid hormones (T4 and T3) by the thyroid gland. Most commonly caused by autoimmune Hashimoto's thyroiditis or post-surgical/radioiodine ablation.",
        "symptoms": ["generalized fatigue and lethargy", "cold intolerance", "unexplained weight gain with decreased appetite", "constipation", "dry coarse skin and hair loss", "bradycardia", "menorrhagia (heavy periods)", "muscle stiffness and carpal tunnel syndrome", "periorbital puffiness"],
        "red_flags": ["Myxedema Coma: Severe hypothermia, marked bradycardia, hypotension, respiratory failure, and progressive altered mental status / coma (Endocrine Emergency, high mortality)"],
        "differentials": ["Depressive Disorder", "Chronic Fatigue Syndrome", "Anemia", "Nephrotic Syndrome", "Heart Failure"],
        "diagnostics": ["Serum Thyroid Stimulating Hormone (TSH) - elevated in primary hypothyroidism (>4.5 mIU/L)", "Free Thyroxine (Free T4) - low in overt, normal in subclinical hypothyroidism", "Anti-Thyroid Peroxidase (Anti-TPO) antibodies for Hashimoto thyroiditis", "Lipid profile (hypercholesterolemia common)"],
        "treatments": ["Levothyroxine (T4) sodium replacement: starting dose 1.6 mcg/kg/day (lower starting dose 25-50 mcg in elderly or coronary artery disease)", "Administer on an empty stomach with a full glass of water, 30-60 minutes before breakfast", "Recheck TSH every 6-8 weeks until euthyroid, then annually", "Avoid co-administration with calcium, iron supplements, or PPIs within 4 hours"],
        "patient_phrases": ["extreme tiredness, gained 10 pounds without eating more and always freezing cold", "sluggish, puffy face, dry skin and chronic constipation", "doctor said my thyroid is underactive TSH 12", "hair falling out and feeling exhausted all day long"],
        "synonyms": ["underactive thyroid", "Hashimoto disease", "thyroid deficiency", "myxedema"],
        "misspellings": ["hypothyroid", "hypothyroidism", "hypothyrodism", "throid problem", "thyriod"],
    },
    {
        "id": "COND-MIGRAINE-011",
        "name": "Migraine Headache (with or without Aura)",
        "icd10": "G43.9",
        "specialty": "Neurology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NICE_UK",
        "urgency": "moderate",
        "summary": "Primary neurovascular headache disorder characterized by recurrent attacks of moderate to severe pulsating, predominantly unilateral pain lasting 4-72 hours, aggravated by routine physical activity, and accompanied by photophobia, phonophobia, and nausea.",
        "symptoms": ["unilateral throbbing or pulsating headache", "photophobia (sensitivity to light)", "phonophobia (sensitivity to sound)", "nausea and vomiting", "visual aura (scintillating scotoma, zigzag lines, blurred vision 5-60 min prior)", "allodynia"],
        "red_flags": ["SNOOP criteria: Systemic symptoms (fever, weight loss), Neurologic deficits, Sudden onset ('thunderclap' headache reaching peak within 1 minute - rule out Subarachnoid Hemorrhage), Older age (>50 new onset), Pattern change (progressive worsening)"],
        "differentials": ["Subarachnoid Hemorrhage", "Tension-Type Headache", "Cluster Headache", "Cerebral Venous Sinus Thrombosis", "Idiopathic Intracranial Hypertension", "Temporal Arteritis"],
        "diagnostics": ["Clinical diagnosis based on ICHD-3 criteria", "Brain MRI/CT indicated if abnormal neurologic exam, thunderclap onset, or atypical persistent aura", "Fundoscopy to rule out papilledema"],
        "treatments": ["Acute Abortive: Triptan (Sumatriptan 50-100mg oral or 6mg SC, Zolmitriptan) combined with NSAID (Naproxen 500mg) early in attack", "Antiemetic: Metoclopramide 10mg or Domperidone 10mg", "Prophylaxis (if >=4 headache days/month): Propranolol 80-160mg daily, Topiramate 50-100mg daily, Amitriptyline 25-75mg at night, or CGRP antagonists (Erenumab, Galcanezumab)"],
        "patient_phrases": ["throbbing pain on one side of my head with flashing lights in eyes", "cannot stand daylight or sound, severe pulsing headache with nausea", "migraine attack lasting 2 days throbbing behind left eye", "sick to my stomach with intense pounding head pain"],
        "synonyms": ["migraine without aura", "migrainous cephalea", "vascular headache", "hemicrania"],
        "misspellings": ["migrain", "migrane", "megraine", "mygraine", "migrain headache"],
    },
    {
        "id": "COND-STROKE-012",
        "name": "Acute Ischemic Stroke & Transient Ischemic Attack (TIA)",
        "icd10": "I63.9",
        "specialty": "Neurology",
        "alternative_specialty": "Emergency Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NICE_UK",
        "urgency": "emergency",
        "summary": "Sudden onset focal neurological deficit resulting from focal cerebral, spinal, or retinal ischemia. Time-critical emergency where rapid restoration of perfusion preserves penumbral brain tissue.",
        "symptoms": ["sudden unilateral facial droop (FAST: Face)", "sudden arm or leg weakness/numbness (FAST: Arm)", "slurred speech, dysarthria, or expressive/receptive aphasia (FAST: Speech)", "sudden loss of vision in one eye (amaurosis fugax)", "sudden vertigo with ataxia"],
        "red_flags": ["FAST positive signs within 4.5 hours of last known normal time (Thrombolysis window)", "Depressed level of consciousness (GCS <10)", "Rapid neurological deterioration", "Concurrent severe headache with vomiting"],
        "differentials": ["Intracranial Hemorrhage", "Seizure with Todd's Paresis", "Hypoglycemia (always check fingerstick blood glucose immediately)", "Complicated Migraine", "Functional Neurological Disorder"],
        "diagnostics": ["Non-contrast Brain CT immediately to exclude hemorrhage", "CT Angiography (CTA) of head and neck for large vessel occlusion (LVO)", "Fingerstick Blood Glucose (exclude hypoglycemia <60 mg/dL)", "Full blood count, coagulation profile (INR/PT/aPTT)", "Brain MRI with Diffusion-Weighted Imaging (DWI)"],
        "treatments": ["IV Thrombolysis: Alteplase (0.9 mg/kg) or Tenecteplase (0.25 mg/kg) within 4.5 hours of onset if no contraindications", "Mechanical Thrombectomy within 6-24 hours for Large Vessel Occlusion (LVO) of anterior circulation", "Antiplatelet therapy: Aspirin 300mg started 24h post-thrombolysis (or immediately if thrombolysis not given)", "Admit to dedicated Acute Stroke Care Unit; maintain permissive hypertension unless BP >220/120"],
        "patient_phrases": ["suddenly half of face is drooping and cannot lift right arm", "words coming out slurred and jumbled, cannot speak clearly", "sudden numbness and weakness in left side of body", "grandpa collapsed and cannot move his arm or talk"],
        "synonyms": ["cerebrovascular accident", "CVA", "brain attack", "ischemic cerebral infarct", "TIA mini-stroke"],
        "misspellings": ["strok", "storke", "cerebral stroke", "ishemic stroke", "paralysis attack"],
    },
    {
        "id": "COND-OA-013",
        "name": "Osteoarthritis (Knee, Hip & Spine)",
        "icd10": "M17.9",
        "specialty": "Orthopedics",
        "alternative_specialty": "Rheumatology",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NICE_UK",
        "urgency": "routine",
        "summary": "Most common chronic joint disorder characterized by progressive loss and destruction of articular cartilage, subchondral bone remodeling, osteophyte formation, and mild synovial inflammation. Common cause of disability in older adults.",
        "symptoms": ["joint pain exacerbated by activity and weight-bearing, relieved by rest", "morning joint stiffness lasting <30 minutes", "joint crepitus (grating sensation on movement)", "bony enlargement (Heberden and Bouchard nodes on hands)", "restricted range of motion and joint instability", "knee buckling"],
        "red_flags": ["Septic Arthritis: Hot, erythematous, acutely swollen joint with high fever and inability to bear weight (Orthopedic Emergency requiring immediate joint aspiration)", "Sudden neurovascular deficit or cauda equina syndrome in severe spinal osteophytosis"],
        "differentials": ["Rheumatoid Arthritis (morning stiffness >1 hour, bilateral symmetrical small joints)", "Gout / Pseudogout", "Bursitis / Tendinopathy", "Meniscal or Ligamentous Tears", "Avascular Necrosis"],
        "diagnostics": ["Plain Radiographs (Weight-bearing X-rays): Joint space narrowing, subchondral sclerosis, subchondral cysts, osteophyte formation", "Blood tests (ESR, CRP, Rheumatoid Factor normal, useful to exclude inflammatory arthropathy)", "Synovial fluid analysis if joint effusion present (non-inflammatory, clear, WBC <2000/mcL)"],
        "treatments": ["Core non-pharmacological: Structured aerobic and muscle-strengthening exercise (quadriceps strengthening), weight management", "Topical NSAID (Topical Diclofenac gel 1-2%) first-line for knee OA", "Oral Paracetamol or oral NSAID (Naproxen 500mg BD + PPI co-prescription) for episodic flares", "Intra-articular corticosteroid injection for acute knee exacerbation", "Referral for Total Knee/Hip Arthroplasty (joint replacement) if severe refractory pain and functional limitation"],
        "patient_phrases": ["severe knee pain when walking down stairs and clicking grinding sounds", "knees stiff every morning for 15 minutes and swollen after gardening", "aching hips when standing up, bone grinding feeling", "wear and tear in knee joints getting worse with age"],
        "synonyms": ["degenerative joint disease", "DJD", "arthrosis", "wear and tear arthritis", "knee OA"],
        "misspellings": ["osteoarthritus", "osteoarthritis", "osteoarthitis", "ostio arthritis", "bone arthritis"],
    },
    {
        "id": "COND-RA-014",
        "name": "Rheumatoid Arthritis",
        "icd10": "M05.9",
        "specialty": "Rheumatology",
        "alternative_specialty": "Orthopedics",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NICE_UK",
        "urgency": "moderate",
        "summary": "Chronic systemic autoimmune inflammatory disease characterized by symmetric, destructive polyarthritis targeting synovial joints, leading to cartilage degradation, bone erosions, joint deformities, and extra-articular manifestations.",
        "symptoms": ["symmetric small joint pain and swelling (MCP, PIP, MTP, wrists)", "prolonged morning joint stiffness lasting >1 hour", "joint warmth, tender swollen squeeze test across metacarpals", "fatigue, low-grade malaise, mild weight loss", "rheumatoid nodules on extensor surfaces"],
        "red_flags": ["Atlantoaxial subluxation with cervical spinal cord compression (quadriparesis, hyperreflexia)", "Rheumatoid vasculitis or scleritis (severe eye pain)", "Acute monoarticular hot joint (septic arthritis superinfection on damaged rheumatoid joint)"],
        "differentials": ["Osteoarthritis", "Psoriatic Arthritis", "Systemic Lupus Erythematosus (SLE)", "Gout / Pseudogout", "Viral Polyarthritis (Parvovirus B19, Chikungunya, Dengue)"],
        "diagnostics": ["Rheumatoid Factor (RF) and Anti-Cyclic Citrullinated Peptide (Anti-CCP / ACPA - 95% specificity)", "Elevated inflammatory markers: ESR and C-Reactive Protein (CRP)", "Plain X-rays of hands and feet (periarticular osteopenia, marginal bone erosions)", "Musculoskeletal Ultrasound (synovial hypertrophy and Doppler power signal)"],
        "treatments": ["Early initiation of Disease-Modifying Antirheumatic Drugs (DMARDs) within 3 months of onset", "First-line: Oral Methotrexate (15-25mg once weekly) + Folic acid 5mg weekly", "Short-course bridging oral Corticosteroids (Prednisolone 10-15mg daily tapered over 6-8 weeks)", "Biological DMARDs (Anti-TNF: Adalimumab, Etanercept; or JAK inhibitors: Tofacitinib) if refractory to conventional synthetic DMARDs", "Target: Clinical remission or low disease activity (DAS28 score <2.6)"],
        "patient_phrases": ["hands and fingers swollen and stiff every morning for over an hour", "pain in both wrists and finger knuckles cannot open jar lids", "swollen symmetric joints in both hands with terrible stiffness", "rheumatologist evaluation needed for positive rheumatoid factor"],
        "synonyms": ["rheumatic arthritis", "chronic polyarthritis", "autoimmune joint disease", "inflammatory arthropathy"],
        "misspellings": ["rhuematoid", "rumatoid arthritis", "reumatoid", "rheumatoid arthritus", "rhematoid"],
    },
    {
        "id": "COND-CKD-015",
        "name": "Chronic Kidney Disease & Sri Lankan CKDu",
        "icd10": "N18.9",
        "specialty": "Nephrology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "SLMA_COLLEGES",
        "urgency": "moderate",
        "summary": "Abnormalities of kidney structure or function present for >3 months with health implications. Includes Chronic Kidney Disease of uncertain etiology (CKDu) prevalent among farming communities in Sri Lanka's North Central Province (Rajarata region).",
        "symptoms": ["early stages usually asymptomatic", "bilateral lower extremity edema (swollen ankles)", "fatigue, lethargy, and anorexia", "foamy or frothy urine (proteinuria)", "nocturia", "generalized pruritus (itching from uremia)", "metallic taste in mouth"],
        "red_flags": ["Acute uremic encephalopathy (asterixis, pericardial friction rub, confusion, seizures)", "Severe hyperkalemia (serum K+ >6.5 mEq/L with peaked T waves on ECG)", "Fluid overload refractory to diuretics (acute pulmonary edema)", "Severe metabolic acidosis"],
        "differentials": ["Acute Kidney Injury", "Nephrotic Syndrome", "Heart Failure", "Cirrhosis with Hepatorenal Syndrome", "End-Stage Renal Disease"],
        "diagnostics": ["Estimated Glomerular Filtration Rate (eGFR) calculated from Serum Creatinine", "Urine Albumin-to-Creatinine Ratio (ACR)", "Renal Ultrasonography (bilateral small echogenic kidneys in CKD; normal/small kidneys with cortical thinning in CKDu)", "Serum Electrolytes (potassium, bicarbonate, phosphate, calcium)", "Hemoglobin for normocytic normochromic anemia of renal failure"],
        "treatments": ["Blood pressure control (target <130/80 mmHg; SBP 120-129 mmHg)", "First-line renal protection: ACE Inhibitor or ARB for patients with albuminuria (ACR >=30 mg/g)", "SGLT2 inhibitor (Dapagliflozin 10mg or Empagliflozin 10mg) proven to retard CKD progression", "Phosphate binders, active Vitamin D, dietary protein moderation (0.8 g/kg/day)", "Renal Replacement Therapy preparation (Hemodialysis, Peritoneal Dialysis, Kidney Transplantation) when eGFR <15 mL/min/1.73m²"],
        "patient_phrases": ["foamy bubbly urine and swelling in both ankles in agricultural area", "elevated creatinine 2.4 on checkup with high blood pressure", "kidney damage screening for farmer in Anuradhapura / Polonnaruwa", "fatigue, puffy eyes, and abnormal kidney function test"],
        "synonyms": ["chronic renal failure", "renal insufficiency", "nephropathy", "CKDu", "Rajarata kidney disease"],
        "misspellings": ["chronik kidney", "kidney failure", "ckd", "nephritis", "kidny disease"],
    },
    {
        "id": "COND-DEPRESSION-016",
        "name": "Major Depressive Disorder & Acute Suicidal Crisis",
        "icd10": "F32.9",
        "specialty": "Psychiatry",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "WHO_GLOBAL",
        "urgency": "urgent",
        "summary": "Common mental health disorder characterized by persistent sadness, loss of interest or pleasure (anhedonia), feelings of worthlessness or guilt, sleep disturbance, cognitive slowing, and potential suicidal ideation.",
        "symptoms": ["persistent depressed mood most of the day for >=2 weeks", "loss of interest or pleasure in almost all activities (anhedonia)", "significant weight loss or gain", "insomnia or hypersomnia", "psychomotor agitation or retardation", "fatigue or loss of energy", "feelings of worthlessness or excessive guilt", "diminished ability to think or concentrate"],
        "red_flags": ["Active suicidal ideation with specific plan, intent, or rehearsal", "History of recent self-harm or lethal attempt", "Command auditory hallucinations urging self-harm", "Severe psychomotor agitation with intense despair or hopelessness", "Access to lethal means (firearms, pesticides, medications)"],
        "differentials": ["Bipolar Affective Disorder (Depressive Phase)", "Hypothyroidism", "Generalized Anxiety Disorder", "Substance/Medication-Induced Depressive Disorder", "Dementia / Pseudodementia"],
        "diagnostics": ["Clinical interview using DSM-5 / ICD-11 diagnostic criteria", "Validated screening scales: PHQ-9 (Patient Health Questionnaire), HAM-D", "Screening for Bipolarity (MDQ) to avoid antidepressant-induced mania", "Thyroid profile (TSH), Vitamin B12, and Full Blood Count"],
        "treatments": ["Safety planning and emergency crisis support (Immediate 24/7 Lifelines: 988 or Sri Lanka National Mental Health Helpline 1926)", "Mild Depression: Evidence-based psychotherapy (Cognitive Behavioral Therapy - CBT, Interpersonal Therapy - IPT)", "Moderate to Severe: Pharmacotherapy with SSRI (Sertraline 50-150mg OD or Escitalopram 10-20mg OD) combined with CBT", "Second-line: SNRI (Venlafaxine, Duloxetine) or Mirtazapine 15-45mg at night", "Electroconvulsive Therapy (ECT) for psychotic depression, severe treatment resistance, or life-threatening suicidal emergencies"],
        "patient_phrases": ["cannot get out of bed, empty hopeless feeling every day for weeks", "crying all the time, nothing brings joy and feeling like a burden", "thoughts that life is not worth living, want to end it all", "severe depression, insomnia, and dark suicidal thoughts"],
        "synonyms": ["clinical depression", "major depression", "unipolar depression", "depressive illness"],
        "misspellings": ["depresion", "depresson", "depresion", "sucide", "suicidal thoughts"],
    },
    {
        "id": "COND-ECZEMA-017",
        "name": "Atopic Dermatitis (Eczema) & Allergic Dermatitis",
        "icd10": "L20.9",
        "specialty": "Dermatology",
        "alternative_specialty": "Allergy & Immunology",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NIH_MEDLINE",
        "urgency": "routine",
        "summary": "Chronic, relapsing, highly pruritic inflammatory skin disease characterized by immune dysregulation, epidermal barrier dysfunction, and frequent association with asthma and allergic rhinitis (atopic triad).",
        "symptoms": ["intense pruritus (itching) often worse at night", "erythematous papules and plaques with excoriations", "dry, scaly, xerotic skin", "lichenification (thickened, leathery skin markings from scratching)", "flexural distribution in adults (antecubital and popliteal fossae, neck)"],
        "red_flags": ["Eczema Herpeticum: Rapid onset of painful grouped vesicular umbilicated lesions with fever (Dermatologic Emergency caused by HSV superinfection; requires immediate systemic acyclovir)", "Secondary bacterial cellulitis with systemic toxicity"],
        "differentials": ["Psoriasis", "Allergic Contact Dermatitis", "Seborrheic Dermatitis", "Scabies", "Cutaneous T-Cell Lymphoma"],
        "diagnostics": ["Clinical diagnosis based on Hanifin and Rajka criteria", "Serum total IgE and allergen-specific IgE (frequently elevated)", "Skin swab for bacterial (Staphylococcus aureus) and viral (HSV PCR) culture if superinfected", "Patch testing for contact allergic dermatitis"],
        "treatments": ["Core foundation: Liberal, frequent application of bland emollient moisturizers (petrolatum, ceramides) immediately after bathing", "Acute flare: Topical Corticosteroids (Hydrocortisone 1% for face; Betamethasone / Mometasone for trunk/limbs) used short-term", "Topical Calcineurin Inhibitors (Tacrolimus 0.1% ointment) for sensitive skin areas (face, eyelids, intertriginous zones)", "Oral sedating antihistamines (Hydroxyzine, Chlorpheniramine) for nocturnal itch", "Systemic biologic therapy (Dupilumab - anti-IL4/IL13) for moderate-to-severe refractory disease"],
        "patient_phrases": ["unbearable itching on skin folds behind knees and elbows with red rash", "dry cracked skin scratching until it bleeds", "eczema flare-up red itchy patches all over arms", "skin rash that will not stop itching at night"],
        "synonyms": ["atopic eczema", "flexural dermatitis", "prurigo", "neurodermatitis"],
        "misspellings": ["exzema", "excema", "ezcema", "dermatitus", "itchy rash"],
    },
    {
        "id": "COND-CATARACT-018",
        "name": "Senile Cataract & Glaucoma (Visual Impairment)",
        "icd10": "H25.9",
        "specialty": "Ophthalmology",
        "alternative_specialty": "General Medicine",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "WHO_GLOBAL",
        "urgency": "routine",
        "summary": "Opacification of the natural crystalline lens of the eye leading to painless progressive decline in visual acuity. Leading cause of reversible blindness worldwide. Primary Angle-Closure Glaucoma is the acute ocular hypertensive emergency counterpart.",
        "symptoms": ["gradual, painless blurring or dimming of vision", "glare and halos around headlights at night", "faded or yellowish color perception", "frequent prescription changes for eyeglasses", "double vision in a single eye (monocular diplopia)"],
        "red_flags": ["Acute Angle-Closure Glaucoma: Sudden severe eye pain, fixed mid-dilated pupil, steamy cornea, headache, vomiting, colored halos around lights (Ophthalmic Emergency requiring immediate IOP reduction to prevent permanent blindness)", "Sudden painless total loss of vision (Central Retinal Artery Occlusion)"],
        "differentials": ["Primary Open-Angle Glaucoma", "Age-Related Macular Degeneration", "Diabetic Retinopathy", "Refractive Error", "Corneal Dystrophy"],
        "diagnostics": ["Slit-lamp biomicroscopy examination", "Best-Corrected Visual Acuity (Snellen chart)", "Tonometry for Intraocular Pressure (IOP normal 10-21 mmHg)", "Dilated funduscopy examination", "Optical Coherence Tomography (OCT) of macula and optic nerve head"],
        "treatments": ["Early stages: Corrective lenses and brighter illumination", "Definitive curative management: Phacoemulsification with Intraocular Lens (IOL) implantation under local anesthesia", "Acute Glaucoma Emergency: IV Mannitol 20%, oral Acetazolamide 500mg, topical Timolol 0.5% + Pilocarpine 2%, immediate laser peripheral iridotomy"],
        "patient_phrases": ["cloudy foggy vision like looking through frosted glass", "trouble driving at night because of blinding glare from headlights", "gradual loss of sight in right eye elderly patient", "sudden intense eye pain and blurred vision with nausea"],
        "synonyms": ["lens opacity", "clouded lens", "visual cataracts", "nuclear sclerotic cataract"],
        "misspellings": ["cataract", "cataracts", "cataract surgery", "glaucoma", "opthalmic"],
    },
    {
        "id": "COND-SINUS-019",
        "name": "Chronic Rhinosinusitis & Allergic Rhinitis",
        "icd10": "J32.9",
        "specialty": "ENT",
        "alternative_specialty": "Allergy & Immunology",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "NICE_UK",
        "urgency": "routine",
        "summary": "Inflammatory condition of the mucosa of the nose and paranasal sinuses persisting for >=12 weeks with or without nasal polyposis, causing nasal obstruction, rhinorrhea, and facial pressure.",
        "symptoms": ["nasal congestion / blockage", "anterior or postnasal drip (phlegm in throat)", "facial pain, fullness, or pressure over cheeks/forehead", "reduced or absent sense of smell (hyposmia / anosmia)", "halitosis", "ear fullness"],
        "red_flags": ["Periorbital cellulitis / orbital abscess (proptosis, ophthalmoplegia, reduced visual acuity)", "Intracranial complications (meningitis, cavernous sinus thrombosis, epidural abscess, severe frontal headache, altered sensorium)"],
        "differentials": ["Allergic Rhinitis", "Vasomotor Rhinitis", "Deviated Nasal Septum", "Nasal Polyposis", "Sinonasal Malignancy", "Dental Odontogenic Sinusitis"],
        "diagnostics": ["Rigid Nasal Endoscopy (visualizing middle meatus purulence, mucosal edema, polyps)", "Non-contrast Coronal CT scan of paranasal sinuses", "Allergy skin prick testing or ImmunoCAP", "Microbiological culture of endoscopically guided middle meatal swab"],
        "treatments": ["High-volume daily nasal saline irrigation (sinus rinse)", "Intranasal Corticosteroid spray (Fluticasone furoate or Mometasone 2 sprays per nostril daily for >=12 weeks)", "Short-course oral corticosteroids for large obstructing polyps", "Functional Endoscopic Sinus Surgery (FESS) for medical treatment failures"],
        "patient_phrases": ["constant blocked nose, thick yellow postnasal drip, and pressure in forehead", "cannot smell anything and cheeks feel full of pressure for months", "chronic sinus infection not getting better with pills", "stuffy nose and mucus constantly draining down back of throat"],
        "synonyms": ["sinusitis", "sinus infection", "rhinosinusitis", "nasal polyp disease"],
        "misspellings": ["sinusitus", "sinusitis", "sinus infection", "rhinitis", "ent sinus"],
    },
    {
        "id": "COND-SNAKE-020",
        "name": "Snakebite Envenomation (Viperidae / Elapidae Envenoming)",
        "icd10": "T63.0",
        "specialty": "Emergency Medicine",
        "alternative_specialty": "Infectious Diseases",
        "emergency_specialty": "Emergency Medicine",
        "source_key": "SLMA_COLLEGES",
        "urgency": "emergency",
        "summary": "High-acuity medical emergency caused by venom inoculation from venomous snakes (Russell's viper, Saw-scaled viper, Hump-nosed pit viper, Cobra, Krait). Major occupational hazard in Sri Lankan agricultural areas requiring rapid antivenom therapy.",
        "symptoms": ["local swelling, blistering, and tissue necrosis at bite site", "fang puncture marks", "neurotoxic signs (bilateral ptosis, ophthalmoplegia, dysarthria, respiratory paralysis)", "hemotoxicity (incoagulable blood, spontaneous bleeding from gums/venipuncture sites)"],
        "red_flags": ["20-minute Whole Blood Clotting Test (20WBCT) uncoagulable", "Rapidly progressive descending neuroparalysis (respiratory muscle compromise)", "Systemic spontaneous hemorrhage", "Acute kidney injury with oliguria", "Hypotension and anaphylactoid shock"],
        "differentials": ["Non-venomous snake bite", "Insect or spider sting", "Centipede bite", "Anaphylaxis to other toxins"],
        "diagnostics": ["20-Minute Whole Blood Clotting Test (20WBCT) performed every 30 minutes initially", "Full Blood Count (thrombocytopenia, leukocytosis)", "Serum Creatinine, Blood Urea, and Electrolytes", "Prothrombin Time / INR", "Urine microscopy for hematuria and myoglobinuria"],
        "treatments": ["Immediate immobilization of bitten limb (splint, NO arterial tourniquets, NO incision/suction)", "Reconstitution and infusion of Polyvalent Snake Antivenom (ASV) as indicated by coagulopathy or neurotoxicity", "Close airway monitoring and early endotracheal intubation for neurotoxic respiratory failure", "Tetanus toxoid booster and supportive renal fluid management"],
        "patient_phrases": ["bitten by snake on foot in paddy field, severe swelling and bleeding from puncture", "eyelids drooping and difficulty breathing after snake bite", "snake bite fang marks swelling spreading up the leg", "bitten by viper, blood not clotting"],
        "synonyms": ["snake envenomation", "viper bite", "cobra bite", "krait bite", "venomous bite"],
        "misspellings": ["snake bite", "snakebite", "snak bite", "antivenom", "viper envenom"],
    }
]

# ── 4. Multi-Symptom Presentations Matrix ─────────────────────────────────────
MULTI_SYMPTOM_CLUSTERS: List[Dict[str, Any]] = [
    {
        "id": "MSC-001",
        "symptoms": ["chest pain", "shortness of breath", "sweating"],
        "conditions": ["Acute Coronary Syndrome", "Pulmonary Embolism", "Acute Heart Failure"],
        "primary_specialty": "Cardiology",
        "emergency_specialty": "Emergency Medicine",
        "urgency": "emergency",
        "rationale": "Cardinal triad of acute cardiopulmonary compromise requiring immediate emergency triage, 12-lead ECG, and cardiac enzymes.",
        "source_key": "ACC_AHA",
    },
    {
        "id": "MSC-002",
        "symptoms": ["fever", "severe headache", "stiff neck"],
        "conditions": ["Acute Bacterial Meningitis", "Viral Encephalitis", "Subarachnoid Hemorrhage"],
        "primary_specialty": "Neurology",
        "emergency_specialty": "Emergency Medicine",
        "urgency": "emergency",
        "rationale": "Meningeal irritation triad indicating central nervous system infection or hemorrhage requiring urgent lumbar puncture and IV antibiotics.",
        "source_key": "NICE_UK",
    },
    {
        "id": "MSC-003",
        "symptoms": ["joint pain", "morning stiffness", "fatigue"],
        "conditions": ["Rheumatoid Arthritis", "Systemic Lupus Erythematosus", "Psoriatic Arthritis", "Osteoarthritis"],
        "primary_specialty": "Rheumatology",
        "alternative_specialty": "Orthopedics",
        "urgency": "moderate",
        "rationale": "Inflammatory polyarthritis presentation requiring autoimmune serology (RF, anti-CCP, ANA) and early DMARD evaluation.",
        "source_key": "NICE_UK",
    },
    {
        "id": "MSC-004",
        "symptoms": ["fever", "retro-orbital pain", "muscle aches", "joint pain"],
        "conditions": ["Dengue Fever", "Chikungunya", "Leptospirosis", "Viral Syndrome"],
        "primary_specialty": "Infectious Diseases",
        "alternative_specialty": "General Medicine",
        "urgency": "urgent",
        "rationale": "Classic arboviral complex in tropical endemic settings. Requires serial full blood counts to detect critical plasma leakage.",
        "source_key": "SL_MOH_EPID",
    },
    {
        "id": "MSC-005",
        "symptoms": ["abdominal pain", "nausea", "vomiting", "bloating"],
        "conditions": ["Acute Gastritis", "Peptic Ulcer Disease", "GERD", "Biliary Colic"],
        "primary_specialty": "Gastroenterology",
        "alternative_specialty": "General Medicine",
        "urgency": "moderate",
        "rationale": "Upper gastrointestinal symptom cluster requiring dietary assessment, H. pylori testing, and acid suppression trial.",
        "source_key": "BSG_ACG",
    },
    {
        "id": "MSC-006",
        "symptoms": ["excessive thirst", "frequent urination", "unexplained weight loss"],
        "conditions": ["Type 2 Diabetes Mellitus", "Type 1 Diabetes Mellitus"],
        "primary_specialty": "Endocrinology",
        "alternative_specialty": "General Medicine",
        "urgency": "routine",
        "rationale": "Classic osmotic symptoms of hyperglycemia indicating diabetes mellitus requiring fasting plasma glucose and HbA1c testing.",
        "source_key": "ADA_DIABETES",
    },
    {
        "id": "MSC-007",
        "symptoms": ["chronic cough", "wheezing", "breathlessness"],
        "conditions": ["Bronchial Asthma", "COPD", "Bronchiectasis"],
        "primary_specialty": "Pulmonology",
        "alternative_specialty": "Allergy & Immunology",
        "urgency": "moderate",
        "rationale": "Lower respiratory obstructive airway symptom cluster requiring spirometry with bronchodilator reversibility testing.",
        "source_key": "GINA_GOLD",
    },
    {
        "id": "MSC-008",
        "symptoms": ["sudden facial droop", "arm weakness", "slurred speech"],
        "conditions": ["Acute Ischemic Stroke", "Transient Ischemic Attack", "Intracerebral Hemorrhage"],
        "primary_specialty": "Neurology",
        "emergency_specialty": "Emergency Medicine",
        "urgency": "emergency",
        "rationale": "FAST positive stroke presentation; ultra-urgent hyperacute stroke protocol pathway with immediate non-contrast brain CT.",
        "source_key": "NICE_UK",
    },
    {
        "id": "MSC-009",
        "symptoms": ["swollen ankles", "shortness of breath", "fatigue"],
        "conditions": ["Congestive Heart Failure", "Chronic Kidney Disease", "Nephrotic Syndrome", "Cirrhosis"],
        "primary_specialty": "Cardiology",
        "alternative_specialty": "Nephrology",
        "urgency": "urgent",
        "rationale": "Fluid retention and systemic congestion syndrome indicating heart failure or renal failure requiring echocardiogram and renal function.",
        "source_key": "ACC_AHA",
    },
    {
        "id": "MSC-010",
        "symptoms": ["calf muscle tenderness", "fever", "red eyes", "yellow skin"],
        "conditions": ["Leptospirosis (Weil's Disease)", "Severe Viral Hepatitis", "Sepsis with Jaundice"],
        "primary_specialty": "Infectious Diseases",
        "alternative_specialty": "Nephrology",
        "urgency": "urgent",
        "rationale": "Pathognomonic presentation of severe leptospirosis with hepatorenal compromise in tropical agricultural settings.",
        "source_key": "SL_MOH_EPID",
    },
]

# ── 5. Red-Flag Emergency Indicators ──────────────────────────────────────────
RED_FLAG_INDICATORS: List[Dict[str, Any]] = [
    {
        "id": "RF-001",
        "concept": "Crushing Retrosternal Chest Pain",
        "category": "cardiovascular",
        "urgency": "emergency",
        "escalation": "Immediate emergency room arrival, 12-lead ECG within 10 mins, emergency cardiology consult, chew 300mg aspirin.",
        "authoritative_source": "ACC/AHA Acute Coronary Syndrome Guidelines",
        "patient_language": [
            "My chest feels like an elephant is sitting on it",
            "Crushing chest pain radiating down left arm",
            "Severe chest pressure and cold sweats",
            "Squeezing heart pain that won't go away",
        ],
    },
    {
        "id": "RF-002",
        "concept": "Acute Focal Neurological Deficit (FAST Signs)",
        "category": "neurological",
        "urgency": "emergency",
        "escalation": "Immediate acute stroke ambulance alert (e.g. 1990 Suwa Seriya in Sri Lanka / 911), urgent brain CT, thrombolysis screening.",
        "authoritative_source": "NICE Stroke and TIA Guidelines NG128",
        "patient_language": [
            "Sudden facial drooping on one side",
            "Cannot lift my right arm suddenly",
            "Speech is completely slurred and words make no sense",
            "Half of my body went numb and weak",
        ],
    },
    {
        "id": "RF-003",
        "concept": "Severe Hypoxia and Stridor",
        "category": "respiratory",
        "urgency": "emergency",
        "escalation": "Immediate high-flow oxygen, airway protection, emergency anesthesia/ENT consult for impending airway obstruction.",
        "authoritative_source": "Resuscitation Council / GINA Guidelines",
        "patient_language": [
            "I cannot get any air into my lungs",
            "High-pitched whistling choking sound when inhaling",
            "Lips and fingertips turning blue and gasping",
            "Suffocating feeling cannot speak full words",
        ],
    },
    {
        "id": "RF-004",
        "concept": "Severe Anaphylaxis / Airway Angioedema",
        "category": "allergy_immunology",
        "urgency": "emergency",
        "escalation": "Immediate intramuscular Adrenaline (Epinephrine 0.5mg 1:1000 IM anterolateral thigh), call emergency services.",
        "authoritative_source": "World Allergy Organization (WAO) Anaphylaxis Guidelines",
        "patient_language": [
            "Throat is closing up after eating peanuts",
            "Tongue and lips swelling huge and wheezing",
            "Allergic reaction cannot swallow or breathe",
            "Covered in hives and feeling dizzy like passing out",
        ],
    },
    {
        "id": "RF-005",
        "concept": "Acute Suicidal Ideation and Self-Harm Crisis",
        "category": "psychiatric",
        "urgency": "emergency",
        "escalation": "Immediate crisis lifeline intervention (988 / Sri Lanka 1926 toll-free 24/7), emergency psychiatric triage, do not leave patient alone.",
        "authoritative_source": "WHO Comprehensive Mental Health Action Plan & Suicide Prevention Guidelines",
        "patient_language": [
            "I want to kill myself tonight",
            "I don't want to live anymore and have a plan to end it",
            "Thinking about suicide constantly and feel like ending it all",
            "I am hurting myself and feel hopeless",
        ],
    },
    {
        "id": "RF-006",
        "concept": "Dengue Warning Signs (Critical Leakage Phase)",
        "category": "infectious_tropical",
        "urgency": "urgent",
        "escalation": "Immediate hospitalization, baseline FBC and hematocrit, supervised isotonic fluid titration, strict fluid balance.",
        "authoritative_source": "Ministry of Health Sri Lanka Dengue Management Guidelines 2023",
        "patient_language": [
            "Severe stomach pain and non-stop vomiting on day 4 of fever",
            "Bleeding from gums and feeling very dizzy standing up with dengue",
            "Extreme weakness and feeling cold clammy skin after fever dropped",
            "Dengue fever patient getting drowsy and refusing fluids",
        ],
    },
]
